[package]
name = "system76-power"
version = "0.1.2"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
dbus = "0.6"
libc = "0.2"
upower_dbus = "0.1"
clap = "2.32.0"
log = "0.4.3"
fern = "0.5.6"

[build-dependencies]
vergen = "0.1.1"
